# Generated by Django 3.0.7 on 2020-07-02 23:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('is_blocked', models.BooleanField(verbose_name='Active or Not')),
                ('rating', models.FloatField(verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=40, verbose_name='House Number/Room Number')),
                ('line2', models.CharField(max_length=60, verbose_name='Block Number/Street Name')),
                ('area', models.CharField(max_length=40, verbose_name='Area')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('landmark', models.CharField(max_length=30, verbose_name='Landmark')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('pin_code', models.IntegerField(verbose_name='Pin Code')),
                ('lon', models.FloatField(max_length=15, verbose_name='Longitude')),
                ('lat', models.FloatField(max_length=15, verbose_name='latitude')),
                ('customer_wise',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
